apiVersion: v1
kind: Service
metadata:
  name: emp-manage-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyAppemp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30500
